CREATE DATABASE crud;
USE crud;
CREATE TABLE user (
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT COLLATE utf8_unicode_ci,
name VARCHAR(30) NOT NULL COLLATE utf8_unicode_ci,
email VARCHAR(60) NOT NULL UNIQUE COLLATE utf8_unicode_ci,
login VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(61) NOT NULL
);
